# Generated by Django 4.2.3 on 2023-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
