# Generated by Django 4.2.3 on 2023-07-22 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docu_upload', '0002_filemodel_date_alter_filemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='shared_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
