# Generated by Django 4.2.3 on 2023-07-22 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docu_upload', '0004_documentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanagement',
            name='shared_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
