# Generated by Django 4.2.3 on 2023-07-22 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docu_upload', '0006_rename_documentmanagement_documentmanagementmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmanagementmodel',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
