# Generated by Django 4.1.3 on 2022-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&psig=AOvVaw09hJ48da0OR4mHSOwvzsyv&ust=1670343231026000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCIi4zdDv4vsCFQAAAAAdAAAAABAD', max_length=500),
        ),
    ]
