# Generated by Django 4.1.3 on 2022-12-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i.pinimg.com/736x/fe/28/24/fe2824904fad4149715d1ee1e2757f91.jpg', max_length=500),
        ),
    ]
